const SHOP_DATA = [
  {
    id: 1,
    name: "MacBook Pro 16 Laptop - Apple M1 Pro chip - 16GB Memory - 1TB SSD - Space Gray",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "2,299.00",
    oprice: "2,699.00",
    percentOff: 15,
    rating: 5,
    inStock: true,
  },
  {
    id: 2,
    name: "Fire Emblem Engage - Nintendo Switch, Nintendo Switch (OLED Model), Nintendo Switch Lite",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "59.99",
    oprice: "59.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 3,
    name: "Nintendo - Switch – OLED Model w/ White Joy-Con - White",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "349.99",
    oprice: "349.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 4,
    name: "CORSAIR - VENGEANCE PRO 32GB (2PK x 16GB) 3600MHz DDR4 C18 DIMM Desktop Memory with RGB lighting",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "99.99",
    oprice: "99.99",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 5,
    name: "Sony - PlayStation 5 Console",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "499.99",
    oprice: "499.99",
    percentOff: "",
    rating: 5,
    inStock: false,
  },
  
  {
    id: 6,
    name: "AMD - Ryzen 7 5800X 4th Gen 8-core, 16-threads Unlocked Desktop Processor Without Cooler",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "249.00",
    oprice: "449.00",
    percentOff: 45,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 7,
    name: "Logitech - G203 LIGHTSYNC Wired Optical Gaming Mouse with 8,000 DPI sensor - Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: 25,
    rating: 3.5,
    inStock: true,
  },
  {
    id: 8,
    name: "Samsung - Galaxy S23 Ultra 256GB (Unlocked) - Phantom Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "1,199.99",
    oprice: "1,199.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 9,
    name: "Apple - iPhone 14 Pro Max 128GB - Space Black",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "1,099.99",
    oprice: "1,099.99",
    percentOff: "",
    rating: 5,
    inStock: false,
  },
  {
    id: 10,
    name: "Google - Pixel 6a 128GB (Unlocked) - Charcoal",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "399.00",
    oprice: "399.99",
    percentOff: "",
    rating: 4,
    inStock: true,
  },
  {
    id: 11,
    name: "LG - UltraGear 32 IPS LED QHD G-SYNC Compatible and AMD FreeSync Premium Pro Monitor with HDR (HDMI, DisplayPort)",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "599.99",
    oprice: "599.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 12,
    name: "CORSAIR - RMx Series RM850x 80 PLUS Gold Fully Modular ATX Power Supply",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "149.99",
    oprice: "149.99",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 13,
    name: "WD - Blue 4TB Internal SATA Hard Drive for Desktops",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "72.00",
    oprice: "89.99",
    percentOff: 20,
    rating: 5,
    inStock: true,
  },
  
  {
    id: 14,
    name: "Alienware - m17 R5 17.3 360Hz FHD Gaming Laptop - AMD Ryzen 9 - 16GB Memory - NVIDIA GeForce RTX 3070 Ti - 1TB SSD - Dark Side of the Moon",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "1,899.99",
    oprice: "2,299.99",
    percentOff: 18,
    rating: 5,
    inStock: true,
  },
];

export default SHOP_DATA;
