const SHOP_DATA = [
  {
    id: 1,
    name: "AppleMacbook Air 13",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "1200.00",
    oprice: "1550.00",
    percentOff: "",
    rating: 4,
    inStock: true,
  },
  {
    id: 2,
    name: "Asus Zenbook 14",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 5,
    inStock: false,
  },
  {
    id: 3,
    name: "Lenovo V15",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 4,
    inStock: true,
  },
  {
    id: 4,
    name: "HP 255 G7",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 5,
    name: "CORSAIR - VENGEANCE PRO 32GB (2PK x 16GB) 3600MHz DDR4 C18 DIMM Desktop Memory with RGB lighting",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "99.99",
    oprice: "99.99",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 6,
    name: "PlayStation 5",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: 25,
    rating: 5,
    inStock: false,
  },
  {
    id: 7,
    name: "Mousepad Hyperx Fury S Pro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: 25,
    rating: 4,
    inStock: true,
  },
  {
    id: 8,
    name: "Ryzen 5 3600x",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: 25,
    rating: 4.5,
    inStock: true,
  },
  {
    id: 9,
    name: "Mouse Logitech g403",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: 25,
    rating: 3.5,
    inStock: true,
  },
  {
    id: 10,
    name: "Moto e7i Power",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "650.00",
    oprice: "700.00",
    percentOff: 25,
    rating: 4,
    inStock: true,
  },
  {
    id: 11,
    name: "iPhone 12 mini",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 5,
    inStock: false,
  },
  {
    id: 12,
    name: "Samsung A12",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 4,
    inStock: true,
  },
  {
    id: 13,
    name: "Nokia 5.4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "37.00",
    oprice: "50.00",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 14,
    name: "PNY - XLR8 Gaming 16GB (2x8GB) 3200MHz DDR4 DRAM (PC4-25600) CL16 1.35V Dual Channel Desktop (DIMM) Memory Kit",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "81.99",
    oprice: "81.99",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 15,
    name: "Xbox Series X 1TB Console",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "499.99",
    oprice: "499.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 16,
    name: "LG - 32 IPS LED QHD FreeSync Monitor with HDR (HDMI, DisplayPort)",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "199.99",
    oprice: "199.99",
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    id: 17,
    name: "CORSAIR - RMx Series RM850x 80 PLUS Gold Fully Modular ATX Power Supply",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "149.99",
    oprice: "149.99",
    percentOff: "",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 18,
    name: "WD - Blue 4TB Internal SATA Hard Drive for Desktops",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "72.00",
    oprice: "89.99",
    percentOff: 20,
    rating: 5,
    inStock: true,
  },
  {
    id: 19,
    name: "Samsung - Galaxy Book Go - 14.0 LED Screen - Qualcomm® Snapdragon™ 7C Gen 2 Processor - 4GB Memory - 128GB eMMC",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "309.99",
    oprice: "309.99",
    percentOff: "",
    rating: 4,
    inStock: true,
  },
  {
    id: 20,
    name: "WD - Blue SN570 1TB Internal SSD PCIe Gen 3 x4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "60.00",
    oprice: "75.00",
    percentOff: 25,
    rating: 5,
    inStock: true,
  },
];

export default SHOP_DATA;
